### ISSUE TITLE
miniAudicle exits immediately on MAC Air running OS/10.6.8

### ISSUE THREAD

**Issue by spencersalazar** [ccrma/miniAudicle#24]
From email correspondence:

I am trying to run the "hello world" application in the first chapter of "Programming for Musicians and Digital Artists".  I am using a Mac Air, running OS version 10.6.8.  

I downloaded (download chuck-1.3.5.0 (includes miniAudicle-1.3.3)) from (http://audicle.cs.princeton.edu/mini/mac/)

It seemed to download and install effortlessly.

I start the VM as directed type in the <<< Hellow World" >>> text, but when I hit ADD SHRED, miniAudicle "quits unexpectedly" with the following error dump:

Am I doing something wrong?  I am looking forward to learning chucK programming, but I only have access to this mac Air (which I love).

Thanks for any help you can provide. 

-Dave

Process:         miniAudicle [353]
Path:            /Applications/miniAudicle.app/Contents/MacOS/miniAudicle
Identifier:      org.miniAudicle.miniAudicle
Version:         1.3.3 (1.3.3)
Code Type:       X86-64 (Native)
Parent Process:  launchd [96]

Date/Time:       2015-01-04 12:28:38.432 -0500
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          416631 sec
Crashes Since Last Report:           9
Per-App Interval Since Last Report:  11768 sec
Per-App Crashes Since Last Report:   9
Anonymous UUID:                      8A816FBB-3DFD-4ED3-846C-20DED4A6EB14

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000
Crashed Thread:  6

Thread 0:  Dispatch queue: com.apple.main-thread
0   libSystem.B.dylib             	0x00007fff8a030a6a __semwait_signal + 10
1   libSystem.B.dylib             	0x00007fff8a0308f9 nanosleep + 148
2   libSystem.B.dylib             	0x00007fff8a030863 usleep + 57
3   org.miniAudicle.miniAudicle   	0x0000000100002bc8 miniAudicle::handle_reply(unsigned long, std::string&) + 248
4   org.miniAudicle.miniAudicle   	0x00000001000027ac miniAudicle::run_code(std::string&, std::string&, std::vector<std::string, std::allocator<std::string> >&, std::string&, unsigned long, unsigned long&, std::string&) + 348
5   org.miniAudicle.miniAudicle   	0x000000010002dc6e -[mADocumentViewController add:] + 1214
6   org.miniAudicle.miniAudicle   	0x0000000100032414 -[mAMultiDocWindowController add:] + 420
7   com.apple.AppKit              	0x00007fff82c67a6b -[NSToolbarButton sendAction:to:] + 75
8   com.apple.AppKit              	0x00007fff828d7205 -[NSToolbarItemViewer mouseDown:] + 5017
9   com.apple.AppKit              	0x00007fff827c43a7 -[NSWindow sendEvent:] + 5409
10  com.apple.AppKit              	0x00007fff826f9afa -[NSApplication sendEvent:] + 4719
11  com.apple.AppKit              	0x00007fff826906de -[NSApplication run] + 474
12  com.apple.AppKit              	0x00007fff826893b0 NSApplicationMain + 364
13  org.miniAudicle.miniAudicle   	0x0000000100001564 start + 52

Thread 1:  Dispatch queue: com.apple.libdispatch-manager
0   libSystem.B.dylib             	0x00007fff8a00ec0a kevent + 10
1   libSystem.B.dylib             	0x00007fff8a010add _dispatch_mgr_invoke + 154
2   libSystem.B.dylib             	0x00007fff8a0107b4 _dispatch_queue_invoke + 185
3   libSystem.B.dylib             	0x00007fff8a0102de _dispatch_worker_thread2 + 252
4   libSystem.B.dylib             	0x00007fff8a00fc08 _pthread_wqthread + 353
5   libSystem.B.dylib             	0x00007fff8a00faa5 start_wqthread + 13

Thread 2:
0   libSystem.B.dylib             	0x00007fff8a00fa2a __workq_kernreturn + 10
1   libSystem.B.dylib             	0x00007fff8a00fe3c _pthread_wqthread + 917
2   libSystem.B.dylib             	0x00007fff8a00faa5 start_wqthread + 13

Thread 3:
0   libSystem.B.dylib             	0x00007fff89ff7982 read$NOCANCEL + 10
1   libSystem.B.dylib             	0x00007fff8a0470ef __sread + 16
2   libSystem.B.dylib             	0x00007fff8a03ee34 _sread + 19
3   libSystem.B.dylib             	0x00007fff8a03ecca __srefill + 41
4   libSystem.B.dylib             	0x00007fff8a05500e fgets + 105
5   org.miniAudicle.miniAudicle   	0x000000010000a844 miniAudicle_Shell_UI::next_command(std::string const&, std::string&) + 84
6   org.miniAudicle.miniAudicle   	0x00000001000d7240 Chuck_Shell::run() + 192
7   org.miniAudicle.miniAudicle   	0x00000001000d7119 shell_cb(void*) + 41
8   libSystem.B.dylib             	0x00007fff8a02efd6 _pthread_start + 331
9   libSystem.B.dylib             	0x00007fff8a02ee89 thread_start + 13

Thread 4:
0   libSystem.B.dylib             	0x00007fff8a030a6a __semwait_signal + 10
1   libSystem.B.dylib             	0x00007fff8a0308f9 nanosleep + 148
2   libSystem.B.dylib             	0x00007fff8a030863 usleep + 57
3   org.miniAudicle.miniAudicle   	0x00000001001786b1 kb_loop(void*) + 113
4   libSystem.B.dylib             	0x00007fff8a02efd6 _pthread_start + 331
5   libSystem.B.dylib             	0x00007fff8a02ee89 thread_start + 13

Thread 5:
0   libSystem.B.dylib             	0x00007fff8a030a6a __semwait_signal + 10
1   libSystem.B.dylib             	0x00007fff8a0308f9 nanosleep + 148
2   libSystem.B.dylib             	0x00007fff8a030863 usleep + 57
3   org.miniAudicle.miniAudicle   	0x00000001000822da Chuck_VM::run() + 458
4   org.miniAudicle.miniAudicle   	0x00000001000015cc vm_cb(void*) + 60
5   libSystem.B.dylib             	0x00007fff8a02efd6 _pthread_start + 331
6   libSystem.B.dylib             	0x00007fff8a02ee89 thread_start + 13

Thread 6 Crashed:
0   ???                           	000000000000000000 0 + 0
1   org.miniAudicle.miniAudicle   	0x000000010008365a Chuck_VM::process_msg(Chuck_Msg*) + 2250
2   org.miniAudicle.miniAudicle   	0x00000001000827ac Chuck_VM::compute() + 812
3   org.miniAudicle.miniAudicle   	0x0000000100082368 Chuck_VM::run(long) + 72
4   org.miniAudicle.miniAudicle   	0x00000001000ec39f Digitalio::cb2(void*, void*, unsigned int, double, unsigned int, void*) + 399
5   org.miniAudicle.miniAudicle   	0x00000001000fd0da RtApiCore::callbackEvent(unsigned int, AudioBufferList const*, AudioBufferList const*) + 314
6   org.miniAudicle.miniAudicle   	0x00000001000fc367 callbackHandler(unsigned int, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) + 23
7   com.apple.audio.CoreAudio     	0x00007fff895e433d HP_IOProc::Call(AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioTimeStamp const&, AudioBufferList*) + 313
8   com.apple.audio.CoreAudio     	0x00007fff895e410f IOA_Device::CallIOProcs(AudioTimeStamp const&, AudioTimeStamp const&, AudioTimeStamp const&) + 303
9   com.apple.audio.CoreAudio     	0x00007fff895e3f45 HP_IOThread::PerformIO(AudioTimeStamp const&, double) + 771
10  com.apple.audio.CoreAudio     	0x00007fff895e1f54 HP_IOThread::WorkLoop() + 1832
11  com.apple.audio.CoreAudio     	0x00007fff895e1827 HP_IOThread::ThreadEntry(HP_IOThread*) + 9
12  com.apple.audio.CoreAudio     	0x00007fff895e1755 CAPThread::Entry(CAPThread*) + 125
13  libSystem.B.dylib             	0x00007fff8a02efd6 _pthread_start + 331
14  libSystem.B.dylib             	0x00007fff8a02ee89 thread_start + 13

Thread 7:
0   com.apple.framework.IOKit     	0x00007fff891b0832 iokit_user_client_trap + 10
1   com.apple.framework.IOKit     	0x00007fff891adee7 IOConnectTrap4 + 30
2   com.apple.audio.CoreAudio     	0x00007fff8960b288 IOA_SingleDevice::ReadInputData(AudioTimeStamp const&, unsigned int) + 198
3   com.apple.audio.CoreAudio     	0x00007fff895e405c IOA_Device::CallIOProcs(AudioTimeStamp const&, AudioTimeStamp const&, AudioTimeStamp const&) + 124
4   com.apple.audio.CoreAudio     	0x00007fff895e3f45 HP_IOThread::PerformIO(AudioTimeStamp const&, double) + 771
5   com.apple.audio.CoreAudio     	0x00007fff895e1f54 HP_IOThread::WorkLoop() + 1832
6   com.apple.audio.CoreAudio     	0x00007fff895e1827 HP_IOThread::ThreadEntry(HP_IOThread*) + 9
7   com.apple.audio.CoreAudio     	0x00007fff895e1755 CAPThread::Entry(CAPThread*) + 125
8   libSystem.B.dylib             	0x00007fff8a02efd6 _pthread_start + 331
9   libSystem.B.dylib             	0x00007fff8a02ee89 thread_start + 13

Thread 8:
0   libSystem.B.dylib             	0x00007fff8a030a6a __semwait_signal + 10
1   libSystem.B.dylib             	0x00007fff8a0308f9 nanosleep + 148
2   libSystem.B.dylib             	0x00007fff8a030863 usleep + 57
3   org.miniAudicle.miniAudicle   	0x00000001000eb071 watch_dog(void*) + 577
4   libSystem.B.dylib             	0x00007fff8a02efd6 _pthread_start + 331
5   libSystem.B.dylib             	0x00007fff8a02ee89 thread_start + 13

**Comment by Mdu7078** [comment]
I can confirm that this is an issue on my own system running Snow Leopard (OS X 10.6.8).  So far I haven't found a way to get it to do anything other than open the editor window...  Running chuck through the command line still works for some files, but fails on most, so it is most likely an issue with chuck's current compatibility with Snow Leopard.

**Comment by spencersalazar** [comment]
Hi,

We have issued a beta release that should fix the issue: https://ccrma.stanford.edu/~spencer/chuck/chuck-1.3.5.1-beta-1.pkg

If you have time/interest, please download+install and let us know if this fixes the issue for you. 

spencer

**Comment by Mdu7078** [comment]
Hey Spencer,
 From what I can see, that package seems to have fixed the issue. Thanks!

Sincerely,
     -- Michael
