### ISSUE TITLE
compilation problem on fedora 23

### ISSUE THREAD

**Issue by ycollet** [ccrma/miniAudicle#28]
I use fedora 23 64 bits to compile miniAudicle. gcc version 5.3.0.
When I compile miniaudicle from source, the following errors occurs:

g++ -c -pipe -D__LINUX_ALSA__ -D__CK_SNDFILE_NATIVE__ -D__LINUX__ -D__PLATFORM_LINUX__ -Ichuck/src -DHAVE_CONFIG_H -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -O3 -w -D_REENTRANT -DHAVE_CONFIG_H -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -Ibuild -Ibuild -o build/miniAudicle.o miniAudicle.cpp
miniAudicle.cpp: Dans la fonction ‘void* vm_cb(void*)’:
miniAudicle.cpp:144:11: erreur: ‘struct Chuck_VM’ has no member named ‘start’
     g_vm->start();
           ^
miniAudicle.cpp:147:10: erreur: ‘g_bbq’ was not declared in this scope
     if( !g_bbq->digi_out()->initialize( ) )
          ^
miniAudicle.cpp:155:5: erreur: ‘g_bbq’ was not declared in this scope
     g_bbq->digi_in()->initialize( );
     ^
miniAudicle.cpp:186:26: erreur: ‘struct Chuck_VM’ has no member named ‘running’
     while( g_vm && g_vm->running() )
                          ^
miniAudicle.cpp:189:13: erreur: ‘g_enable_realtime_audio’ was not declared in this scope
         if( g_enable_realtime_audio )
             ^
miniAudicle.cpp:204:14: erreur: ‘all_stop’ was not declared in this scope
     all_stop();
              ^
miniAudicle.cpp:209:9: erreur: ‘g_enable_realtime_audio’ was not declared in this scope
     if( g_enable_realtime_audio )
         ^
miniAudicle.cpp: Dans la fonction membre ‘long unsigned int miniAudicle::start_vm()’:
miniAudicle.cpp:980:15: erreur: ‘g_bbq’ was not declared in this scope
         bbq = g_bbq = new BBQ;
               ^
miniAudicle.cpp:993:55: erreur: ‘g_enable_realtime_audio’ was not declared in this scope
         EM_log( CK_LOG_SYSTEM, "probing '%s' audio subsystem...", g_enable_realtime_audio ? "real-time" : "fake-time" );
                                                       ^
makefile.qt-alsa:1198: recipe for target 'build/miniAudicle.o' failed

**Comment by spencersalazar** [comment]
Thanks for reporting this. There were some recent changes to chuck's internal code organization that required matching changes in miniAudicle. This is probably related to that. We will get it sorted out!

**Comment by spencersalazar** [comment]
Hi- one possible issue- are you compiling from miniAudicle Git master? If so, keep in mind it is necessary to 'git submodule update' if/when miniAudicle's chuck submodule has been updated (which is definitely the case recently).

**Comment by ycollet** [comment]
After a git submodule update, the problem is still the same

**Comment by spencersalazar** [comment]
Hmm, unfortunately Im not able to replicate the errors you are seeing on the latest source in Git (Ubuntu 14.04, gcc-4.8.4 + gcc-5.3.0). Is there any other info you think might be relevant to why the build is failing?

**Comment by ycollet** [comment]
I will try to reclone the repository and build it again.
The git status tells me that no files where modified.

**Comment by spencersalazar** [comment]
Yeah its pretty weird. Works for me in Fedora also, so not sure what the problem could be or how to further debug.

**Comment by ycollet** [comment]
I deleted the clone and clone again the repo. Now it works fine.
The clone was really old (years old). Maybe post submodule. That was maybe the problem.
