### ISSUE TITLE
Stop virtual machine on Windows

### ISSUE THREAD

**Issue by MichaPau** [ccrma/miniAudicle#30]
Hello,

It is impossible to stop the virtual machine on Windows 7 (64bit)
The "Stop virtual machine" button in the VM window is disabled and greyed out as well as the menu entry in Menu->ChucK->StopVirtualMachine.

The command Alt+ just adds a new Shred.

![chuck_vm](https://cloud.githubusercontent.com/assets/4903900/20039806/e5bd1fb6-a44a-11e6-8838-f8b379904fa7.png)

It's not that an issue because one can always close and re-start miniAudicle for sure,
but I thought I can get my key-bindings back when stopping the VM.
(see [issue 29](https://github.com/ccrma/miniAudicle/issues/29) )

**Comment by MichaPau** [comment]
ccrma/chuck#47

**Comment by gewang** [comment]
this issue has been resolved as of 1.5.0.0; it was part of the upgrade from Qt4 to Qt6 by @spencersalazar
